// <auto-generated />
using System;
using Garage2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Garage2._0.Migrations
{
    [DbContext(typeof(Garage2_0Context))]
    partial class Garage2_0ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garage2._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("NumOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<int>("VehicleType")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ArrivalTime = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Make = "Dodge",
                            Model = "Nitro TR 4/4",
                            NumOfWheels = 4,
                            RegNum = "FZK678",
                            VehicleType = 3
                        },
                        new
                        {
                            ID = 2,
                            ArrivalTime = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Make = "Camaro",
                            Model = "SS",
                            NumOfWheels = 4,
                            RegNum = "FZK677",
                            VehicleType = 3
                        },
                        new
                        {
                            ID = 3,
                            ArrivalTime = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Orange",
                            Make = "Harley Davidson",
                            Model = "NightRod",
                            NumOfWheels = 2,
                            RegNum = "MKT677",
                            VehicleType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
